version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  receiver-service:
    build: ./receiver-service
    container_name: receiver-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/pubsub_assignment
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  listener-service:
    build: ./listener-service
    container_name: listener-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/pubsub_assignment
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data:
